// Icons used by components or referenced dynamically must be registered here.
// The build plugin uses these lists to import only the required icons instead
// of bundling the entire icon library.
//
// TODO: Move icon definitions into a separate icon library package.
export type IconStyles =
  | 'fa-duotone'
  | 'fa-duotoneli'
  | 'fa-duotoneso'
  | 'fa-duotoneth'
  | 'fa-light'
  | 'fa-regular'
  | 'fa-sharp'
  | 'fa-sharpduotone'
  | 'fa-sharpduotoneli'
  | 'fa-sharpduotoneso'
  | 'fa-sharpduotoneth'
  | 'fa-sharpli'
  | 'fa-sharpso'
  | 'fa-sharpth'
  | 'fa-solid'
  | 'fa-thin'
  | 'huge-bulk'
  | 'huge-duotone'
  | 'huge-regular'
  | 'huge-rounded'
  | 'huge-sharp'
  | 'huge-solid'
  | 'huge-solidsh'
  | 'huge-twotone'
  | 'iconoir-regular'
  | 'iconoir-solid'
  | 'ion-outline'
  | 'ion-sharp'
  | 'isocons-left'
  | 'isocons-right'
  | 'isocons-top'
  | 'isocons-duotoneleft'
  | 'isocons-duotoneright'
  | 'isocons-duotonetop'
  | 'isocons-duotonesharpleft'
  | 'isocons-duotonesharpright'
  | 'isocons-duotonesharptop'
  | 'isocons-sharpleft'
  | 'isocons-sharpright'
  | 'isocons-sharptop'
  | 'isocons-solidleft'
  | 'isocons-solidright'
  | 'isocons-solidtop'
  | 'isocons-solidsharpleft'
  | 'isocons-solidsharpright'
  | 'isocons-solidsharptop'
  | 'lucide-regular'
  | 'magi-duotone'
  | 'magi-light'
  | 'magi-regular'
  | 'magi-solid'
  | 'md-outlined'
  | 'md-round'
  | 'md-sharp'
  | 'md-solid'
  | 'md-twotone'
  | 'ming-cute'
  | 'ming-cutefi'
  | 'ming-cuteli'
  | 'ming-duotone'
  | 'ming-light'
  | 'ming-regular'
  | 'ming-sharp'
  | 'ming-solid'
  | 'ming-twotone'
  | 'ph-bold'
  | 'ph-duotone'
  | 'ph-light'
  | 'ph-regular'
  | 'ph-solid'
  | 'ph-thin'
  | 'solar-broken'
  | 'solar-duotone'
  | 'solar-duotoneso'
  | 'solar-regular'
  | 'solar-solid'
  | 'uni-light'
  | 'uni-mono'
  | 'uni-regular'
  | 'uni-solid'

export const defaultIconStyle: IconStyles = 'huge-bulk'

export const componentIcons = [
  'default-accordion-default',
  'default-accordion-plus',
  'default-accordion-chevron',
  'default-accordion-circle',
]

export const dynamicIcons = []
